services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: imp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: dev
      LOG_LEVEL: debug

      DB_DRIVER: postgres
      DB_DSN: "host=postgres user=postgres password=123456 dbname=imp_db port=5432 sslmode=disable"

      GIN_PORT: 3000

      REDIS_HOST: redis

      STOREKEEPER_API_KEY: 82b81a84c19b8d17e6c0a4b9a3553a4e
      MANAGER_API_KEY: 0a04630fdcfebe605c3b3c9ece58b824 

    ports:
      - "3000:3000"

volumes:
  postgres_data:
