services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: imp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imp_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - imp_network

  redis:
    image: redis:7
    container_name: inventory-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - imp_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: dev
      LOG_LEVEL: debug
      
      DB_DRIVER: postgres
      DB_DSN: "host=postgres user=postgres password=123456 dbname=imp_db port=5432 sslmode=disable"

      GIN_PORT: 3000

      REDIS_HOST: redis

      STOREKEEPER_API_KEY: 82b81a84c19b8d17e6c0a4b9a3553a4e
      MANAGER_API_KEY: 0a04630fdcfebe605c3b3c9ece58b824

    ports:
      - "3000:3000"
    networks:
      - imp_network
  
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - imp_network
 
  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - imp_network
 
  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    restart: always
    ports:
      - "9080:9080"
    volumes:
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/logs:/var/log/backend_logs
    depends_on:
      - loki
    networks:
      - imp_network
 
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    networks:
      - imp_network


volumes:
  postgres_data:
  grafana_data:
  loki_data:

networks:
  imp_network:
    driver: bridge
