// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/inventory-movements/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads a CSV file containing stock movements (IN, OUT, ADJUST) to process in batch.\nThe engine validates the CSV format and groups rows by item ID.\nMovements are then processed concurrently via a worker pool, ensuring non-negative stock limits and avoiding duplicate external IDs.\nReturns a summary of the batch import execution including success/fail counts and row-level details.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movements"
                ],
                "summary": "Import inventory movements from a CSV file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file to import (required, max size: 5MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/entity.ImportBatchResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseBadRequest"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseConflict"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseInternal"
                        }
                    }
                }
            }
        },
        "/v1/items": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of inventory items.\nSupports rich filtering by SKU, name, quantity ranges, low-stock status, and custom sorting options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "List and filter inventory items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by product name substring",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by product SKU prefix",
                        "name": "sku",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter for items currently running below their safety threshold",
                        "name": "low_stock",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field name to sort by (e.g., name, sku, current_stock)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction: asc or desc",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination (Default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records per page (Default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Item"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseBadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseInternal"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a new product SKU in the warehouse.\nEnsures SKU is unique and initial stock levels are non-negative.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Register a new inventory item",
                "parameters": [
                    {
                        "description": "Product registration details including SKU, name, initial stock, and safety threshold.",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/core.APIResponseNoResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseBadRequest"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseItemConflict"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseInternal"
                        }
                    }
                }
            }
        },
        "/v1/items/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches details of a single inventory item, including current stock and safety threshold, using its unique ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Retrieve an inventory item by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unique database ID of the inventory item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.APIResponseNoPage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/entity.Item"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseBadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseItemNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseInternal"
                        }
                    }
                }
            }
        },
        "/v1/items/{id}/movements": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches paginated inventory movement records associated with a specific item.\nSupports pagination through ` + "`" + `page` + "`" + ` and ` + "`" + `limit` + "`" + ` query parameters.\nReturns movement history ordered according to repository configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Retrieve inventory movement history by item ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unique identifier of the inventory item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination. Must be greater than 0. Default is 1.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of movement records per page. Must be greater than 0. Default is 10.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "pagination": {
                                            "$ref": "#/definitions/core.Pagination"
                                        },
                                        "result": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Movement"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseBadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseItemNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseInternal"
                        }
                    }
                }
            }
        },
        "/v1/reports/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches a summary of the most actively moved inventory items for a specific date.\nImplements a stale-while-revalidate caching mechanism to ensure high availability and graceful fallback during database disruptions.\nIf the requested date is the current system date, the response will additionally include items that have fallen below the low-stock threshold.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Retrieve the daily active inventory report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target date for the report in YYYY-MM-DD format. Defaults to the current date if omitted.",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of top active items to retrieve. Must be a strictly positive integer. Default is 5.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/core.APIResponseNoPage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/entity.TopActiveItemsResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseBadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponseInternal"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "pagination": {
                    "$ref": "#/definitions/core.Pagination"
                },
                "result": {}
            }
        },
        "core.APIResponseNoPage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "result": {}
            }
        },
        "core.APIResponseNoResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "core.ErrResponseBadRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_INPUT"
                },
                "message": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "core.ErrResponseConflict": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "DUPLICATE_TRANSACTION"
                },
                "message": {
                    "type": "string",
                    "example": "duplicate transaction detected"
                }
            }
        },
        "core.ErrResponseInternal": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INTERNAL_ERROR"
                },
                "message": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "core.ErrResponseItemConflict": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "DUPLICATE_SKU"
                },
                "message": {
                    "type": "string",
                    "example": "duplicate SKU detected"
                }
            }
        },
        "core.ErrResponseItemNotFound": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ITEM_NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "item not found"
                }
            }
        },
        "core.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "entity.CreateItemRequest": {
            "type": "object",
            "required": [
                "name",
                "sku"
            ],
            "properties": {
                "low_stock_threshold": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "sku": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "entity.DailyItemSummary": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "item_id": {
                    "type": "integer",
                    "example": 1
                },
                "summary_date": {
                    "type": "string",
                    "example": "2026-05-22T00:00:00Z"
                },
                "total_adjust": {
                    "type": "integer",
                    "example": 10
                },
                "total_in": {
                    "type": "integer",
                    "example": 100
                },
                "total_out": {
                    "type": "integer",
                    "example": 40
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "entity.ImportBatchFailedInfo": {
            "type": "object",
            "properties": {
                "error_report_file": {
                    "type": "string"
                },
                "total_failed": {
                    "type": "integer"
                }
            }
        },
        "entity.ImportBatchResult": {
            "type": "object",
            "properties": {
                "duplicate": {
                    "type": "integer",
                    "example": 0
                },
                "failed_info": {
                    "$ref": "#/definitions/entity.ImportBatchFailedInfo"
                },
                "rejected": {
                    "type": "integer",
                    "example": 1
                },
                "success": {
                    "type": "integer",
                    "example": 999
                },
                "total": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "entity.Item": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "current_stock": {
                    "type": "integer",
                    "example": 150
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "low_stock_threshold": {
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "type": "string",
                    "example": "Laptop Dell XPS 15"
                },
                "sku": {
                    "type": "string",
                    "example": "SKU-001"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "entity.Movement": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "external_id": {
                    "type": "string",
                    "example": "TXN-120001"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "item_id": {
                    "type": "integer",
                    "example": 1
                },
                "movement_time": {
                    "type": "string",
                    "example": "2026-05-22T08:00:00Z"
                },
                "movement_type": {
                    "enum": [
                        "IN",
                        "OUT",
                        "ADJUST"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.MovementType"
                        }
                    ],
                    "example": "IN"
                },
                "note": {
                    "type": "string",
                    "example": "Initial stock import batch 1"
                },
                "quantity": {
                    "type": "integer",
                    "example": 50
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "entity.MovementType": {
            "type": "string",
            "enum": [
                "IN",
                "OUT",
                "ADJUST"
            ],
            "x-enum-varnames": [
                "MovementTypeIn",
                "MovementTypeOut",
                "MovementTypeAdjust"
            ]
        },
        "entity.TopActiveItemsResult": {
            "type": "object",
            "properties": {
                "low_stock_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Item"
                    }
                },
                "top_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.DailyItemSummary"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token. Example: \"Bearer eyJhbGci...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Inventory Movement Processing API",
	Description:      "API for inventory movement processing system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
